// Generated by gencpp from file pcl_icp/get_object_pose.msg
// DO NOT EDIT!


#ifndef PCL_ICP_MESSAGE_GET_OBJECT_POSE_H
#define PCL_ICP_MESSAGE_GET_OBJECT_POSE_H

#include <ros/service_traits.h>


#include <pcl_icp/get_object_poseRequest.h>
#include <pcl_icp/get_object_poseResponse.h>


namespace pcl_icp
{

struct get_object_pose
{

typedef get_object_poseRequest Request;
typedef get_object_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_object_pose
} // namespace pcl_icp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pcl_icp::get_object_pose > {
  static const char* value()
  {
    return "ce62f562fe862ddbebe5377023767cb7";
  }

  static const char* value(const ::pcl_icp::get_object_pose&) { return value(); }
};

template<>
struct DataType< ::pcl_icp::get_object_pose > {
  static const char* value()
  {
    return "pcl_icp/get_object_pose";
  }

  static const char* value(const ::pcl_icp::get_object_pose&) { return value(); }
};


// service_traits::MD5Sum< ::pcl_icp::get_object_poseRequest> should match
// service_traits::MD5Sum< ::pcl_icp::get_object_pose >
template<>
struct MD5Sum< ::pcl_icp::get_object_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_icp::get_object_pose >::value();
  }
  static const char* value(const ::pcl_icp::get_object_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_icp::get_object_poseRequest> should match
// service_traits::DataType< ::pcl_icp::get_object_pose >
template<>
struct DataType< ::pcl_icp::get_object_poseRequest>
{
  static const char* value()
  {
    return DataType< ::pcl_icp::get_object_pose >::value();
  }
  static const char* value(const ::pcl_icp::get_object_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pcl_icp::get_object_poseResponse> should match
// service_traits::MD5Sum< ::pcl_icp::get_object_pose >
template<>
struct MD5Sum< ::pcl_icp::get_object_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pcl_icp::get_object_pose >::value();
  }
  static const char* value(const ::pcl_icp::get_object_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pcl_icp::get_object_poseResponse> should match
// service_traits::DataType< ::pcl_icp::get_object_pose >
template<>
struct DataType< ::pcl_icp::get_object_poseResponse>
{
  static const char* value()
  {
    return DataType< ::pcl_icp::get_object_pose >::value();
  }
  static const char* value(const ::pcl_icp::get_object_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCL_ICP_MESSAGE_GET_OBJECT_POSE_H
