set(_CATKIN_CURRENT_PACKAGE "pcl_icp")
set(pcl_icp_VERSION "0.0.0")
set(pcl_icp_MAINTAINER "michael <michael@todo.todo>")
set(pcl_icp_PACKAGE_FORMAT "2")
set(pcl_icp_BUILD_DEPENDS "message_generation" "cv_bridge" "geometry_msgs" "pcl_conversions" "message_generation" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(pcl_icp_BUILD_EXPORT_DEPENDS )
set(pcl_icp_BUILDTOOL_DEPENDS "catkin")
set(pcl_icp_BUILDTOOL_EXPORT_DEPENDS )
set(pcl_icp_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf" "message_runtime")
set(pcl_icp_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs" "geometry_msgs" "tf")
set(pcl_icp_TEST_DEPENDS )
set(pcl_icp_DOC_DEPENDS )
set(pcl_icp_URL_WEBSITE "")
set(pcl_icp_URL_BUGTRACKER "")
set(pcl_icp_URL_REPOSITORY "")
set(pcl_icp_DEPRECATED "")