set(_CATKIN_CURRENT_PACKAGE "Dlib_detection")
set(Dlib_detection_VERSION "0.0.0")
set(Dlib_detection_MAINTAINER "richtong888 <richtong888@todo.todo>")
set(Dlib_detection_PACKAGE_FORMAT "2")
set(Dlib_detection_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(Dlib_detection_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(Dlib_detection_BUILDTOOL_DEPENDS "catkin")
set(Dlib_detection_BUILDTOOL_EXPORT_DEPENDS )
set(Dlib_detection_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(Dlib_detection_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(Dlib_detection_TEST_DEPENDS )
set(Dlib_detection_DOC_DEPENDS )
set(Dlib_detection_URL_WEBSITE "")
set(Dlib_detection_URL_BUGTRACKER "")
set(Dlib_detection_URL_REPOSITORY "")
set(Dlib_detection_DEPRECATED "")