# CMake generated Testfile for 
# Source directory: /home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test
# Build directory: /home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_cv_bridge_gtest_cv_bridge-utest "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/gtest-cv_bridge-utest.xml" "--return-code" "/home/richtong888/nose_decect/catkin_ws/devel_isolated/cv_bridge/lib/cv_bridge/cv_bridge-utest --gtest_output=xml:/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/gtest-cv_bridge-utest.xml")
set_tests_properties(_ctest_cv_bridge_gtest_cv_bridge-utest PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;6;catkin_add_gtest;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;0;")
add_test(_ctest_cv_bridge_nosetests_enumerants.py "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/nosetests-enumerants.py.xml" "--return-code" "\"/home/richtong888/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/enumerants.py --with-xunit --xunit-file=/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/nosetests-enumerants.py.xml")
set_tests_properties(_ctest_cv_bridge_nosetests_enumerants.py PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/melodic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;13;catkin_add_nosetests;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;0;")
add_test(_ctest_cv_bridge_nosetests_conversions.py "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/nosetests-conversions.py.xml" "--return-code" "\"/home/richtong888/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/conversions.py --with-xunit --xunit-file=/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/nosetests-conversions.py.xml")
set_tests_properties(_ctest_cv_bridge_nosetests_conversions.py PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/melodic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;14;catkin_add_nosetests;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;0;")
add_test(_ctest_cv_bridge_nosetests_python_bindings.py "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/nosetests-python_bindings.py.xml" "--return-code" "\"/home/richtong888/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/python_bindings.py --with-xunit --xunit-file=/home/richtong888/nose_decect/catkin_ws/build_isolated/cv_bridge/test_results/cv_bridge/nosetests-python_bindings.py.xml")
set_tests_properties(_ctest_cv_bridge_nosetests_python_bindings.py PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/melodic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;15;catkin_add_nosetests;/home/richtong888/nose_decect/catkin_ws/src/vision_opencv/cv_bridge/test/CMakeLists.txt;0;")
